### ISSUE TITLE
Temporary files that are useless and annoying

### ISSUE THREAD

**Issue by amirisback** [Skyproject12/ExerciseKotlin-JetPackLibrary#1]
Attention : Try write in your .gitignore on root project, and delete .idea folder

*.iml
/.gradle
.gradle
.idea
/local.properties
/.idea/libraries
/.idea/modules.xml
/.idea/workspace.xml
.DS_Store
build
/build
/captures
.externalNativeBuild

built application files
.apk
.ap_

files for the dex VM
*.dex

Java class files
*.class

generated files
bin/
gen/
.externalNativeBuild/

Local configuration file (sdk path, etc)
local.properties
app/version.properties

# SonarQube
.sonar/

**Comment by amirisback** [comment]
Attention : Try write in your .gitignore on root project, and delete .idea folder.
.iml also

**Comment by Skyproject12** [comment]
Thanks for your advice

Pada tanggal Jum, 20 Des 2019 17.24 Muhammad Faisal Amir <
notifications@github.com menulis:
